export const DUMMY_CLIENTS_LIST: any[] = [
  {
    counseleeName: '권가은',
    counseleeId: 'asdf2347s',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'asdf2897s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '백찬이',
    counseleeId: '13534efsdf2362',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '남시연',
    counseleeId: 'assdfweredf2897s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '권가은',
    counseleeId: 'asdfs2347s',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'asdfs2897s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '권가은',
    counseleeId: '13534sefsdf2362',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'assdfwesredf2897s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '권가은',
    counseleeId: 'asdfs23417s',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'asdfs28971s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '권가은',
    counseleeId: '13534sefsdf12362',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'assdfwesr1edf2897s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '권가은',
    counseleeId: 'asdfs123417s',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'asdf1s28971s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '권가은',
    counseleeId: '13534sefs1df12362',
    start: '23-06-28',
    inProgress: true,
    counselingDate: 'THU',
    counselingTime: '07:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
  {
    counseleeName: '김서연',
    counseleeId: 'assdfwesr1e1df2897s',
    start: '23-06-20',
    inProgress: false,
    counselingDate: 'FRI',
    counselingTime: '13:00',
    goal: '우울감이 있어 해소하고 싶음',
  },
];
